export const TYPES = [
  "Spell Card",
  "Trap Card",
  "Normal Monster",
  "Normal Tuner Monster",
  "Effect Monster",
  "Tuner Monster",
  "Flip Effect Monster",
  "Flip Tuner Effect Monster",
  "Spirit Monster",
  "Union Effect Monster",
  "Gemini Monster",
  "Pendulum Effect Monster",
  "Pendulum Normal Monster",
  "Pendulum Tuner Effect Monster",
  "Ritual Monster",
  "Ritual Effect Monster",
  "Toon Monster",
  "Fusion Monster",
  "Synchro Monster",
  "Synchro Tuner Monster",
  "Synchro Pendulum Effect Monster",
  "XYZ Monster",
  "XYZ Pendulum Effect Monster",
  "Link Monster",
  "Pendulum Flip Effect Monster",
  "Pendulum Effect Fusion Monster",
];
